CREATE TABLE Groups (
  	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name NVARCHAR(15)
);

CREATE TABLE Students (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name NVARCHAR(15),
  	groupId INTEGER,
    FOREIGN KEY(groupId) REFERENCES 'Groups'(id)
);